spring:
  data:
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      password: ''
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/unihis?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true
    username: root
    password: 111111
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: java


sa-token:
  token-name: sa-token
  active-timeout: -1
  is-concurrent: true
  is-share: false
  is-log: false
  token-style: uuid

wx:
  appid: ''
  secret: ''

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
# 阿里OSS
ali-oss:
  endpoint: 'oss-cn-hangzhou.aliyuncs.com'
  accessKey: ''
  secretKey: ''
  bucketName: 'img-'
  domain: 'https://img-.oss-cn-hangzhou.aliyuncs.com'


server:
  port: 9090